name: Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: "Publish library"
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          fetch-depth: 0

      - name: Install rye
        uses: phi-friday/install-rye@v1.4
        id: install-rye
        with:
          python_version: ${{ matrix.python-version }}
          use_uv: true

      - name: Build package
        run: |
          rye install dunamai
          VERSION=$(dunamai from any --no-metadata --style pep440).$(date +"%Y%m%d")
          rye version $VERSION
          rye build

      - name: Release to PyPI
        run: |
          rye publish --yes \
          --username __token__ --token ${{ secrets.PYPI_API_TOKEN }}